// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cookies/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de21adcecce421c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de21adcecce421c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetBuildingsRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (m *QueryGetBuildingsRequest) Reset()         { *m = QueryGetBuildingsRequest{} }
func (m *QueryGetBuildingsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBuildingsRequest) ProtoMessage()    {}
func (*QueryGetBuildingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de21adcecce421c, []int{2}
}
func (m *QueryGetBuildingsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBuildingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBuildingsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBuildingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBuildingsRequest.Merge(m, src)
}
func (m *QueryGetBuildingsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBuildingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBuildingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBuildingsRequest proto.InternalMessageInfo

func (m *QueryGetBuildingsRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type QueryGetBuildingsResponse struct {
	Buildings Buildings `protobuf:"bytes,1,opt,name=buildings,proto3" json:"buildings"`
}

func (m *QueryGetBuildingsResponse) Reset()         { *m = QueryGetBuildingsResponse{} }
func (m *QueryGetBuildingsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBuildingsResponse) ProtoMessage()    {}
func (*QueryGetBuildingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de21adcecce421c, []int{3}
}
func (m *QueryGetBuildingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBuildingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBuildingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBuildingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBuildingsResponse.Merge(m, src)
}
func (m *QueryGetBuildingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBuildingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBuildingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBuildingsResponse proto.InternalMessageInfo

func (m *QueryGetBuildingsResponse) GetBuildings() Buildings {
	if m != nil {
		return m.Buildings
	}
	return Buildings{}
}

type QueryAllBuildingsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBuildingsRequest) Reset()         { *m = QueryAllBuildingsRequest{} }
func (m *QueryAllBuildingsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllBuildingsRequest) ProtoMessage()    {}
func (*QueryAllBuildingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de21adcecce421c, []int{4}
}
func (m *QueryAllBuildingsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBuildingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBuildingsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBuildingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBuildingsRequest.Merge(m, src)
}
func (m *QueryAllBuildingsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBuildingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBuildingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBuildingsRequest proto.InternalMessageInfo

func (m *QueryAllBuildingsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllBuildingsResponse struct {
	Buildings  []Buildings         `protobuf:"bytes,1,rep,name=buildings,proto3" json:"buildings"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBuildingsResponse) Reset()         { *m = QueryAllBuildingsResponse{} }
func (m *QueryAllBuildingsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllBuildingsResponse) ProtoMessage()    {}
func (*QueryAllBuildingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de21adcecce421c, []int{5}
}
func (m *QueryAllBuildingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBuildingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBuildingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBuildingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBuildingsResponse.Merge(m, src)
}
func (m *QueryAllBuildingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBuildingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBuildingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBuildingsResponse proto.InternalMessageInfo

func (m *QueryAllBuildingsResponse) GetBuildings() []Buildings {
	if m != nil {
		return m.Buildings
	}
	return nil
}

func (m *QueryAllBuildingsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetCostRequest struct {
	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Building string `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"`
}

func (m *QueryGetCostRequest) Reset()         { *m = QueryGetCostRequest{} }
func (m *QueryGetCostRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCostRequest) ProtoMessage()    {}
func (*QueryGetCostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de21adcecce421c, []int{6}
}
func (m *QueryGetCostRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCostRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCostRequest.Merge(m, src)
}
func (m *QueryGetCostRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCostRequest proto.InternalMessageInfo

func (m *QueryGetCostRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryGetCostRequest) GetBuilding() string {
	if m != nil {
		return m.Building
	}
	return ""
}

type QueryGetCostResponse struct {
	Cost int64 `protobuf:"varint,1,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (m *QueryGetCostResponse) Reset()         { *m = QueryGetCostResponse{} }
func (m *QueryGetCostResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCostResponse) ProtoMessage()    {}
func (*QueryGetCostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de21adcecce421c, []int{7}
}
func (m *QueryGetCostResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCostResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCostResponse.Merge(m, src)
}
func (m *QueryGetCostResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCostResponse proto.InternalMessageInfo

func (m *QueryGetCostResponse) GetCost() int64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "TheMarstonConnell.cookies.cookies.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "TheMarstonConnell.cookies.cookies.QueryParamsResponse")
	proto.RegisterType((*QueryGetBuildingsRequest)(nil), "TheMarstonConnell.cookies.cookies.QueryGetBuildingsRequest")
	proto.RegisterType((*QueryGetBuildingsResponse)(nil), "TheMarstonConnell.cookies.cookies.QueryGetBuildingsResponse")
	proto.RegisterType((*QueryAllBuildingsRequest)(nil), "TheMarstonConnell.cookies.cookies.QueryAllBuildingsRequest")
	proto.RegisterType((*QueryAllBuildingsResponse)(nil), "TheMarstonConnell.cookies.cookies.QueryAllBuildingsResponse")
	proto.RegisterType((*QueryGetCostRequest)(nil), "TheMarstonConnell.cookies.cookies.QueryGetCostRequest")
	proto.RegisterType((*QueryGetCostResponse)(nil), "TheMarstonConnell.cookies.cookies.QueryGetCostResponse")
}

func init() { proto.RegisterFile("cookies/query.proto", fileDescriptor_8de21adcecce421c) }

var fileDescriptor_8de21adcecce421c = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x9b, 0xed, 0xda, 0xb5, 0xa3, 0x07, 0x99, 0x2d, 0x58, 0x83, 0x44, 0xcd, 0x41, 0xdd,
	0xb5, 0x64, 0x68, 0xad, 0x2b, 0xa8, 0x07, 0xb7, 0x0b, 0x56, 0x10, 0xa5, 0x06, 0x4f, 0x1e, 0x94,
	0x49, 0x3b, 0x64, 0x83, 0x69, 0x26, 0xdb, 0x99, 0x88, 0x4b, 0xe9, 0x65, 0x3f, 0x81, 0xe0, 0xb7,
	0xf0, 0x03, 0x78, 0x15, 0xc4, 0xc3, 0x1e, 0x17, 0xbc, 0x78, 0x12, 0x69, 0xfd, 0x20, 0xd2, 0xc9,
	0x4b, 0x76, 0x43, 0x83, 0x9b, 0xba, 0xa7, 0x4e, 0x92, 0xf7, 0xfe, 0xef, 0xf7, 0x9f, 0xf7, 0x1e,
	0x45, 0xeb, 0x7d, 0xce, 0xdf, 0x79, 0x4c, 0x90, 0xbd, 0x88, 0x8d, 0xf6, 0xad, 0x70, 0xc4, 0x25,
	0xc7, 0x37, 0x5e, 0xed, 0xb2, 0xe7, 0x74, 0x24, 0x24, 0x0f, 0x76, 0x78, 0x10, 0x30, 0xdf, 0xb7,
	0x20, 0x2c, 0xf9, 0xd5, 0x6b, 0x2e, 0x77, 0xb9, 0x8a, 0x26, 0xf3, 0x53, 0x9c, 0xa8, 0x5f, 0x75,
	0x39, 0x77, 0x7d, 0x46, 0x68, 0xe8, 0x11, 0x1a, 0x04, 0x5c, 0x52, 0xe9, 0xf1, 0x40, 0xc0, 0xd7,
	0xcd, 0x3e, 0x17, 0x43, 0x2e, 0x88, 0x43, 0x05, 0x8b, 0xeb, 0x91, 0xf7, 0x4d, 0x87, 0x49, 0xda,
	0x24, 0x21, 0x75, 0xbd, 0x40, 0x05, 0x43, 0x6c, 0x2d, 0xe1, 0x0a, 0xe9, 0x88, 0x0e, 0x13, 0x85,
	0xcb, 0xc9, 0x5b, 0x27, 0xf2, 0xfc, 0x81, 0x17, 0xb8, 0xf0, 0xc1, 0xac, 0x21, 0xfc, 0x72, 0x2e,
	0xd8, 0x53, 0xd1, 0x36, 0xdb, 0x8b, 0x98, 0x90, 0xe6, 0x1b, 0xb4, 0x9e, 0x79, 0x2b, 0x42, 0x1e,
	0x08, 0x86, 0xbb, 0xa8, 0x12, 0xab, 0xd6, 0xb5, 0xeb, 0xda, 0xed, 0x0b, 0xad, 0x0d, 0xeb, 0x54,
	0xbf, 0x56, 0x2c, 0xd1, 0x59, 0x3d, 0xfc, 0x75, 0xad, 0x64, 0x43, 0xba, 0xd9, 0x40, 0x75, 0xa5,
	0xdf, 0x65, 0xb2, 0x93, 0x00, 0x41, 0x6d, 0x7c, 0x09, 0x95, 0x23, 0x6f, 0xa0, 0x2a, 0x54, 0xed,
	0xf9, 0xd1, 0x1c, 0xa2, 0x2b, 0x39, 0xd1, 0xc0, 0xd4, 0x43, 0xd5, 0xd4, 0x13, 0x60, 0x35, 0x0a,
	0x60, 0xa5, 0x42, 0x40, 0x76, 0x2c, 0x62, 0x3a, 0x00, 0xb7, 0xed, 0xfb, 0x0b, 0x70, 0x4f, 0x10,
	0x3a, 0xbe, 0x71, 0x28, 0x77, 0xd3, 0x8a, 0xdb, 0x63, 0xcd, 0xdb, 0x63, 0xc5, 0xe3, 0x00, 0xed,
	0xb1, 0x7a, 0xd4, 0x65, 0x90, 0x6b, 0x9f, 0xc8, 0x34, 0xbf, 0x68, 0xe0, 0x29, 0x5b, 0x24, 0xdf,
	0x53, 0xf9, 0xcc, 0x9e, 0x70, 0x37, 0xc3, 0xbd, 0xa2, 0xb8, 0x6f, 0x9d, 0xca, 0x1d, 0xe3, 0x64,
	0xc0, 0x9f, 0xc1, 0x64, 0x74, 0x99, 0xdc, 0xe1, 0x42, 0x26, 0xf7, 0x52, 0x47, 0x6b, 0x74, 0x30,
	0x18, 0x31, 0x21, 0xa0, 0x71, 0xc9, 0x23, 0xd6, 0xd1, 0xf9, 0x04, 0x43, 0xd5, 0xad, 0xda, 0xe9,
	0xb3, 0xb9, 0x89, 0x6a, 0x59, 0x31, 0xf0, 0x8f, 0xd1, 0x6a, 0x9f, 0x0b, 0xa9, 0xa4, 0xca, 0xb6,
	0x3a, 0xb7, 0x0e, 0x2a, 0xe8, 0x9c, 0x0a, 0xc6, 0x9f, 0x35, 0x54, 0x89, 0xa7, 0x0a, 0xdf, 0x2b,
	0x70, 0x2b, 0x8b, 0xe3, 0xad, 0x6f, 0x2d, 0x9b, 0x16, 0x73, 0x99, 0xcd, 0x83, 0x1f, 0x7f, 0x3e,
	0xad, 0xdc, 0xc1, 0x1b, 0x64, 0x21, 0x9f, 0x24, 0x0b, 0x96, 0x5d, 0x3f, 0xfc, 0x4d, 0x43, 0xd5,
	0xb4, 0x2f, 0xf8, 0x61, 0xd1, 0xc2, 0x39, 0x8b, 0xa1, 0x3f, 0xfa, 0xbf, 0x64, 0x60, 0x7f, 0xa0,
	0xd8, 0xdb, 0xb8, 0x55, 0x80, 0x3d, 0x9d, 0x1b, 0x32, 0x8e, 0xbc, 0xc1, 0x04, 0x7f, 0xd5, 0xd0,
	0xc5, 0x54, 0x71, 0xdb, 0xf7, 0x8b, 0xfb, 0xc8, 0xd9, 0xa1, 0xe2, 0x3e, 0xf2, 0x76, 0xc3, 0x6c,
	0x2b, 0x1f, 0x16, 0x6e, 0x2c, 0xe3, 0x03, 0x7f, 0xd7, 0xd0, 0x1a, 0x4c, 0x19, 0xde, 0x5a, 0xe2,
	0x1e, 0x4f, 0xcc, 0xb8, 0x7e, 0x7f, 0xe9, 0x3c, 0x40, 0x7e, 0xaa, 0x90, 0x3b, 0xf8, 0x71, 0x01,
	0x64, 0x97, 0xc9, 0xb7, 0xf3, 0x79, 0x27, 0x63, 0x58, 0xa0, 0x09, 0x19, 0x27, 0x36, 0x26, 0x9d,
	0x17, 0x87, 0x53, 0x43, 0x3b, 0x9a, 0x1a, 0xda, 0xef, 0xa9, 0xa1, 0x7d, 0x9c, 0x19, 0xa5, 0xa3,
	0x99, 0x51, 0xfa, 0x39, 0x33, 0x4a, 0xaf, 0xdb, 0xae, 0x27, 0x77, 0x23, 0xc7, 0xea, 0xf3, 0xe1,
	0x3f, 0xaa, 0x7c, 0x48, 0x4f, 0x72, 0x3f, 0x64, 0xc2, 0xa9, 0xa8, 0x3f, 0x81, 0xbb, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xda, 0xd6, 0x03, 0xd3, 0xcd, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Buildings by index.
	Buildings(ctx context.Context, in *QueryGetBuildingsRequest, opts ...grpc.CallOption) (*QueryGetBuildingsResponse, error)
	// Queries a list of Buildings items.
	BuildingsAll(ctx context.Context, in *QueryAllBuildingsRequest, opts ...grpc.CallOption) (*QueryAllBuildingsResponse, error)
	// Queries a list of GetCost items.
	GetCost(ctx context.Context, in *QueryGetCostRequest, opts ...grpc.CallOption) (*QueryGetCostResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/TheMarstonConnell.cookies.cookies.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Buildings(ctx context.Context, in *QueryGetBuildingsRequest, opts ...grpc.CallOption) (*QueryGetBuildingsResponse, error) {
	out := new(QueryGetBuildingsResponse)
	err := c.cc.Invoke(ctx, "/TheMarstonConnell.cookies.cookies.Query/Buildings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BuildingsAll(ctx context.Context, in *QueryAllBuildingsRequest, opts ...grpc.CallOption) (*QueryAllBuildingsResponse, error) {
	out := new(QueryAllBuildingsResponse)
	err := c.cc.Invoke(ctx, "/TheMarstonConnell.cookies.cookies.Query/BuildingsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCost(ctx context.Context, in *QueryGetCostRequest, opts ...grpc.CallOption) (*QueryGetCostResponse, error) {
	out := new(QueryGetCostResponse)
	err := c.cc.Invoke(ctx, "/TheMarstonConnell.cookies.cookies.Query/GetCost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Buildings by index.
	Buildings(context.Context, *QueryGetBuildingsRequest) (*QueryGetBuildingsResponse, error)
	// Queries a list of Buildings items.
	BuildingsAll(context.Context, *QueryAllBuildingsRequest) (*QueryAllBuildingsResponse, error)
	// Queries a list of GetCost items.
	GetCost(context.Context, *QueryGetCostRequest) (*QueryGetCostResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Buildings(ctx context.Context, req *QueryGetBuildingsRequest) (*QueryGetBuildingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buildings not implemented")
}
func (*UnimplementedQueryServer) BuildingsAll(ctx context.Context, req *QueryAllBuildingsRequest) (*QueryAllBuildingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildingsAll not implemented")
}
func (*UnimplementedQueryServer) GetCost(ctx context.Context, req *QueryGetCostRequest) (*QueryGetCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCost not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TheMarstonConnell.cookies.cookies.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Buildings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBuildingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Buildings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TheMarstonConnell.cookies.cookies.Query/Buildings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Buildings(ctx, req.(*QueryGetBuildingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BuildingsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllBuildingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BuildingsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TheMarstonConnell.cookies.cookies.Query/BuildingsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BuildingsAll(ctx, req.(*QueryAllBuildingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TheMarstonConnell.cookies.cookies.Query/GetCost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCost(ctx, req.(*QueryGetCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TheMarstonConnell.cookies.cookies.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Buildings",
			Handler:    _Query_Buildings_Handler,
		},
		{
			MethodName: "BuildingsAll",
			Handler:    _Query_BuildingsAll_Handler,
		},
		{
			MethodName: "GetCost",
			Handler:    _Query_GetCost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cookies/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetBuildingsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBuildingsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBuildingsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Uid) > 0 {
		i -= len(m.Uid)
		copy(dAtA[i:], m.Uid)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Uid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBuildingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBuildingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBuildingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Buildings.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllBuildingsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBuildingsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBuildingsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllBuildingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBuildingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBuildingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Buildings) > 0 {
		for iNdEx := len(m.Buildings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Buildings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCostRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCostRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCostRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Building) > 0 {
		i -= len(m.Building)
		copy(dAtA[i:], m.Building)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Building)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCostResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCostResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCostResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Cost != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Cost))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetBuildingsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBuildingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Buildings.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllBuildingsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllBuildingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Buildings) > 0 {
		for _, e := range m.Buildings {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCostRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Building)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCostResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cost != 0 {
		n += 1 + sovQuery(uint64(m.Cost))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBuildingsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBuildingsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBuildingsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBuildingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBuildingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBuildingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buildings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Buildings.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBuildingsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBuildingsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBuildingsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBuildingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBuildingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBuildingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buildings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buildings = append(m.Buildings, Buildings{})
			if err := m.Buildings[len(m.Buildings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCostRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCostRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCostRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Building", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Building = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCostResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCostResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCostResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cost", wireType)
			}
			m.Cost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cost |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
